import { ModelSection } from '../../../components/ui/ModelSection'
import { GMMViz } from '../visualizations/GMMViz'
import { GMMMath } from '../content/gmmMath'

export function GMMSection() {
  return (
    <ModelSection
      id="gmm"
      title="Gaussian Mixture Models"
      subtitle="Model data as a mixture of overlapping Gaussian distributions."
      intuition={
        <div className="max-w-2xl">
          <p className="text-text-secondary leading-relaxed">
            Imagine the data was generated by{' '}
            <strong className="text-text-primary">k overlapping, soft-edged clouds</strong>. Each cloud is a
            Gaussian distribution with its own center, shape, and size. GMM tries to find these clouds —
            and for each data point, it says "there's a 70% chance you came from cloud A and 30% from cloud B."
          </p>
          <p className="mt-3 text-text-secondary leading-relaxed">
            Unlike K-Means, GMM gives you <em>probabilities</em>, not hard boundaries. Points between
            clusters get mixed colors — reflecting genuine uncertainty about which group they belong to.
          </p>
        </div>
      }
      mechanism={<GMMViz />}
      math={<GMMMath />}
      whenToUse={
        <div className="max-w-2xl">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <h5 className="text-sm font-medium text-success mb-2">Strengths</h5>
              <ul className="space-y-2 text-sm text-text-secondary">
                <li>Soft / probabilistic assignments</li>
                <li>Handles elliptical clusters</li>
                <li>Models cluster shape & orientation</li>
                <li>Principled probabilistic framework</li>
              </ul>
            </div>
            <div>
              <h5 className="text-sm font-medium text-error mb-2">Limitations</h5>
              <ul className="space-y-2 text-sm text-text-secondary">
                <li>Assumes Gaussian-shaped clusters</li>
                <li>Sensitive to initialization</li>
                <li>Computationally heavier than K-Means</li>
                <li>Can converge to poor local optima</li>
              </ul>
            </div>
          </div>
        </div>
      }
    />
  )
}
